import { Request, Response } from 'express';
import mongoose from 'mongoose';
import Order, { IOrder } from '../models/Order';
import Cart from '../models/Cart';
import Product from '../models/Product';
import Delivery from '../models/Delivery';
import { groupItemsByStore, createChildOrders, syncParentStatus } from '../utils/orderSplitter';

/**
 * @route   POST /api/orders
 * @desc    Create an order from the current cart (student only). 
 *          Triggers the order splitting engine for multi-vendor carts.
 */
export const createOrder = async (req: Request, res: Response): Promise<void> => {
    try {
        const { deliveryAddress, notes = '', orderType = 'delivery' } = req.body;

        // Validate orderType
        if (!['delivery', 'takeaway'].includes(orderType)) {
            res.status(400).json({ message: 'Order type must be "delivery" or "takeaway"' });
            return;
        }

        // Delivery address required only for delivery orders
        if (orderType === 'delivery' && !deliveryAddress) {
            res.status(400).json({ message: 'Delivery address is required for delivery orders' });
            return;
        }

        // Get the user's cart
        const cart = await Cart.findOne({ user: req.user!._id });
        if (!cart || cart.items.length === 0) {
            res.status(400).json({ message: 'Cart is empty' });
            return;
        }

        // Validate inventory for all items
        for (const item of cart.items) {
            const product = await Product.findById(item.product);
            if (!product) {
                res.status(400).json({ message: `Product ${item.product} no longer exists` });
                return;
            }
            if (product.inventory < item.quantity) {
                res.status(400).json({
                    message: `Insufficient inventory for "${product.name}". Available: ${product.inventory}, Requested: ${item.quantity}`
                });
                return;
            }
        }

        // Group cart items by store (the splitting analysis step)
        const groupedItems = await groupItemsByStore(cart.items);

        // Calculate overall total
        let overallTotal = 0;
        for (const items of groupedItems.values()) {
            overallTotal += items.reduce((sum, item) => sum + (item.product.price * item.quantity), 0);
        }

        // Prepare items with names for the parent order (required by schema validation)
        const itemsWithNames = await Promise.all(cart.items.map(async (item) => {
            const product = await Product.findById(item.product);
            return {
                product: item.product,
                name: product ? product.name : 'Unknown Product',
                price: item.priceAtAdd,
                quantity: item.quantity
            };
        }));

        // Create parent order
        const parentOrder = await Order.create({
            orderNumber: '',  // auto-generated by pre-validate hook
            user: req.user!._id,
            type: 'parent',
            items: itemsWithNames,
            subtotal: overallTotal,
            commission: 0,
            total: overallTotal,
            status: 'pending',
            paymentStatus: 'paid',  // Simplified for now
            deliveryAddress: orderType === 'delivery' ? deliveryAddress : 'Self Pickup',
            notes,
            orderType
        }) as IOrder;

        // Create child orders (one per vendor/store)
        const childOrders = await createChildOrders(
            req.user!._id as mongoose.Types.ObjectId,
            parentOrder._id as mongoose.Types.ObjectId,
            groupedItems,
            orderType === 'delivery' ? deliveryAddress : 'Self Pickup',
            notes,
            orderType
        );

        // Decrement inventory for all ordered items
        for (const item of cart.items) {
            await Product.findByIdAndUpdate(item.product, {
                $inc: { inventory: -item.quantity }
            });
        }

        // Clear the cart
        cart.items = [];
        await cart.save();

        // Return the parent order with child orders
        res.status(201).json({
            parentOrder,
            childOrders,
            message: `Order placed successfully! Split into ${childOrders.length} vendor order(s).`
        });
    } catch (error) {
        res.status(500).json({ message: error instanceof Error ? error.message : 'Server Error' });
    }
};

/**
 * @route   GET /api/orders/my
 * @desc    Get own order history (student only, parent orders)
 */
export const getMyOrders = async (req: Request, res: Response): Promise<void> => {
    try {
        const orders = await Order.find({
            user: req.user!._id,
            type: 'parent'
        })
            .populate('items.product', 'name images')
            .sort({ createdAt: -1 });

        // For each parent, also get child order summaries
        const ordersWithChildren = await Promise.all(
            orders.map(async (order) => {
                const children = await Order.find({ parentOrder: order._id })
                    .populate('store', 'name')
                    .select('store status subtotal items');
                return { ...order.toObject(), childOrders: children };
            })
        );

        res.json(ordersWithChildren);
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

/**
 * @route   GET /api/orders/:id
 * @desc    Get order details (student for own, vendor for own store's)
 */
export const getOrderById = async (req: Request, res: Response): Promise<void> => {
    try {
        const order = await Order.findById(req.params.id)
            .populate('items.product', 'name images price')
            .populate('store', 'name')
            .populate('user', 'name email');

        if (!order) {
            res.status(404).json({ message: 'Order not found' });
            return;
        }

        // Check access: student can see own orders, vendor can see own store's orders
        const userId = (req as any).user._id.toString();
        const isOwner = order.user && (order.user as any)._id.toString() === userId;
        const isVendor = (req as any).user.role === 'shopkeeper' && (req as any).store &&
            order.store && (order.store as any)._id.toString() === (req as any).store._id.toString();
        const isAdmin = (req as any).user.role === 'admin';

        if (!isOwner && !isVendor && !isAdmin) {
            res.status(403).json({ message: 'Not authorized to view this order' });
            return;
        }

        // Look up any associated delivery
        const delivery = await Delivery.findOne({ order: order._id })
            .populate('driver', 'name');

        const orderData = order.toObject();
        const responseData: any = { ...orderData };

        // Include delivery info if exists
        if (delivery) {
            responseData.delivery = {
                _id: delivery._id,
                status: delivery.status,
                driverName: (delivery.driver as any)?.name,
                pickupAddress: delivery.pickupAddress,
                deliveryAddress: delivery.deliveryAddress,
                deliveryFee: delivery.deliveryFee,
                estimatedTime: delivery.estimatedTime,
            };
        }

        // If parent order, include children
        if (order.type === 'parent') {
            const children = await Order.find({ parentOrder: order._id })
                .populate('store', 'name')
                .select('store status subtotal commission items orderNumber');
            responseData.childOrders = children;
        }

        res.json(responseData);
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

/**
 * @route   GET /api/vendor/orders
 * @desc    Get orders for vendor's own store (child orders only)
 */
export const getVendorOrders = async (req: Request, res: Response): Promise<void> => {
    try {
        const { status } = req.query;
        const filter: any = {
            store: req.store!._id,
            type: 'child'
        };

        if (status && status !== 'all') {
            filter.status = status;
        }

        const orders = await Order.find(filter)
            .populate('user', 'name email')
            .populate('items.product', 'name images')
            .sort({ createdAt: -1 });

        res.json(orders);
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

/**
 * @route   PUT /api/vendor/orders/:id/status
 * @desc    Update child order status (vendor only)
 */
export const updateOrderStatus = async (req: Request, res: Response): Promise<void> => {
    try {
        const { status } = req.body;
        const validStatuses = ['confirmed', 'preparing', 'ready', 'dispatched', 'delivered', 'cancelled'];

        if (!status || !validStatuses.includes(status)) {
            res.status(400).json({ message: `Invalid status. Must be one of: ${validStatuses.join(', ')}` });
            return;
        }

        const order = await Order.findOne({
            _id: req.params.id,
            store: req.store!._id,
            type: 'child'
        });

        if (!order) {
            res.status(404).json({ message: 'Order not found or does not belong to your store' });
            return;
        }

        order.status = status;
        await order.save();

        // Sync parent order status
        if (order.parentOrder) {
            await syncParentStatus(order.parentOrder as mongoose.Types.ObjectId);
        }

        res.json({ message: `Order status updated to '${status}'`, order });
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};

/**
 * @route   GET /api/admin/orders
 * @desc    Get all orders (admin only)
 */
export const getAllOrders = async (req: Request, res: Response): Promise<void> => {
    try {
        const { type = 'parent', status } = req.query;
        const filter: any = {};

        if (type) filter.type = type;
        if (status && status !== 'all') filter.status = status;

        const orders = await Order.find(filter)
            .populate('user', 'name email')
            .populate('store', 'name')
            .sort({ createdAt: -1 });

        res.json(orders);
    } catch (error) {
        res.status(500).json({ message: 'Server Error' });
    }
};
