




import mongoose from 'mongoose';
import Order from '../models/Order';
import Store from '../models/Store';
import { ICartItem } from '../models/Cart';
import Product from '../models/Product';

interface PopulatedCartItem {
    product: {
        _id: mongoose.Types.ObjectId;
        name: string;
        price: number;
        store: mongoose.Types.ObjectId;
    };
    quantity: number;
    priceAtAdd: number;
}

/**
 * Groups cart items by their store ID.
 * Returns a Map where key = storeId string, value = array of cart items.
 */
export async function groupItemsByStore(cartItems: ICartItem[]): Promise<Map<string, PopulatedCartItem[]>> {
    const groups = new Map<string, PopulatedCartItem[]>();

    // Populate all products to get store info
    const productIds = cartItems.map(item => item.product);
    const products = await Product.find({ _id: { $in: productIds } }).select('name price store');

    const productMap = new Map((products as any[]).map(p => [p._id.toString(), p]));

    for (const item of cartItems) {
        const product = productMap.get(item.product.toString());
        if (!product) continue;

        const storeId = product.store.toString();
        const populated: PopulatedCartItem = {
            product: {
                _id: product._id as mongoose.Types.ObjectId,
                name: product.name,
                price: product.price,
                store: product.store
            },
            quantity: item.quantity,
            priceAtAdd: item.priceAtAdd
        };

        if (!groups.has(storeId)) {
            groups.set(storeId, []);
        }
        groups.get(storeId)!.push(populated);
    }

    return groups;
}

/**
 * Creates child orders for each vendor from grouped cart items.
 * Returns the array of created child Order documents.
 */
export async function createChildOrders(
    userId: mongoose.Types.ObjectId,
    parentOrderId: mongoose.Types.ObjectId,
    groupedItems: Map<string, PopulatedCartItem[]>,
    deliveryAddress: string,
    notes: string,
    orderType: 'delivery' | 'takeaway'
): Promise<any[]> {
    const childOrders = [];

    for (const [storeId, items] of groupedItems) {
        // Get the store's commission rate
        const store = await Store.findById(storeId);
        const commissionRate = store?.commissionRate || 10; // Default 10%

        // Calculate subtotal for this vendor's items
        const subtotal = items.reduce((sum, item) => sum + (item.priceAtAdd * item.quantity), 0);
        const commission = Math.round(subtotal * commissionRate) / 100;
        const total = subtotal; // Delivery fee is handled at parent level or could be per-vendor

        const childOrder = await Order.create({
            // orderNumber auto-generated by pre-validate hook
            user: userId,
            type: 'child',
            parentOrder: parentOrderId,
            store: storeId,
            items: items.map(item => ({
                product: item.product._id,
                name: item.product.name,
                price: item.priceAtAdd,
                quantity: item.quantity
            })),
            subtotal,
            commission,
            total,
            status: 'pending',
            paymentStatus: 'pending',
            deliveryAddress: orderType === 'delivery' ? deliveryAddress : 'Self Pickup',
            notes,
            orderType
        });

        childOrders.push(childOrder);
    }

    return childOrders;
}

/**
 * Syncs parent order status based on all child order statuses.
 * Call this whenever a child order status changes.
 */
export async function syncParentStatus(parentOrderId: mongoose.Types.ObjectId): Promise<void> {
    const childOrders = await Order.find({ parentOrder: parentOrderId, type: 'child' });

    if (childOrders.length === 0) return;

    const statuses = childOrders.map(o => o.status);

    let parentStatus: string;

    if (statuses.every(s => s === 'delivered')) {
        parentStatus = 'delivered';
    } else if (statuses.every(s => s === 'cancelled')) {
        parentStatus = 'cancelled';
    } else if (statuses.some(s => s === 'dispatched' || s === 'delivered')) {
        parentStatus = 'dispatched'; // partially fulfilled
    } else if (statuses.some(s => s === 'preparing' || s === 'ready')) {
        parentStatus = 'preparing';
    } else if (statuses.some(s => s === 'confirmed')) {
        parentStatus = 'confirmed';
    } else {
        parentStatus = 'pending';
    }

    await Order.findByIdAndUpdate(parentOrderId, { status: parentStatus });
}
